apiVersion: v1
kind: Namespace
metadata:
  name: spema
  labels:
    app.kubernetes.io/name: spema
    app.kubernetes.io/part-of: spema-ledger
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
