apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spema-data-pvc
  namespace: spema
  labels:
    app.kubernetes.io/name: spema
    app.kubernetes.io/part-of: spema-ledger
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
